version: 2.1

commands:
################### Helpers
  save_e2e_artifacts:
    steps:
      - run:
          name: Compress the artifacts for easier downloading
          when: always
          command: for file in ~/bichard7-next-tests/screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - run:
          name: Create the saved_artifacts directory
          when: always
          command: mkdir ./saved_artifacts
      - run:
          name: Move the gzipped files across
          when: always
          command: mv ~/bichard7-next-tests/screenshots/*.tar.gz ./saved_artifacts/
      - store_artifacts:
          path: /home/circleci/project/saved_artifacts

  build_data_jar:
    description: Package the standing data into a jar file
    steps:
      - run:
          name: Package data with maven
          command: mvn package --no-transfer-progress

  checkout_bichard_repo:
    description: Check out the bichard7-next repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 34:9c:fd:c3:53:22:35:9e:07:60:6b:55:85:97:0d:18
      - run:
          name: Clone bichard7-next
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next.git ~/bichard7-next

  build_bichard:
    description: Build the Bichard application and copy in the latest standing data
    steps:
      - run:
          name: Copy data JAR into place
          command: |
            cp $(find ~/project/target -type f -name '*.jar' -and ! -name '*sources.jar') ~/bichard7-next/jars/bichard7-next-data.jar
      - run:
          name: Replace gradle data dependency with reference to local JAR
          working_directory: ~/bichard7-next
          command: |
            sed -i -r "s|^.*name: 'bichard7-next-data'.*$|    implementation files('../jars/bichard7-next-data.jar')|" bichard-backend/build.gradle
      - run:
          name: Build Bichard application
          working_directory: ~/bichard7-next
          command: make build-ci

  fetch_docker_image:
    parameters:
      image:
        type: string
    steps:
      - run:
          name: Fetch the <<parameters.image>> image
          working_directory: ~/bichard7-next
          command: bash scripts/fetch_docker_image.sh <<parameters.image>>

  fetch_docker_images:
    description: Fetch all of the required docker images from ECR
    steps:
      - fetch_docker_image:
          image: beanconnect
      - fetch_docker_image:
          image: nginx-auth-proxy
      - fetch_docker_image:
          image: pncemulator
      - fetch_docker_image:
          image: user-service
      - fetch_docker_image:
          image: ui

  install_tests:
    steps:
      - run:
          name: Checkout the tests repo
          command: git clone --depth 1 https://github.com/ministryofjustice/bichard7-next-tests.git ~/bichard7-next-tests
      # restore_cache technically operates at the Job level, not the step level.
      - restore_cache:
          name: Restore bichard7-next-tests dependencies from cache
          key: b7-tests-deps-{{ checksum "~/bichard7-next-tests/package-lock.json" }}
      - run:
          name: Install test dependencies
          working_directory: ~/bichard7-next-tests
          command: npm i
      - run: # Puppeteer downloads Chromium from Google Cloud Storage by default, which can be flaky.
          name: Retry install test dependencies
          working_directory: ~/bichard7-next-tests
          when: on_fail
          command: npm i
      - save_cache:
          name: Save bichard7-next-tests dependencies to cache
          working_directory: ~/bichard7-next-tests
          key: b7-tests-deps-{{ checksum "~/bichard7-next-tests/package-lock.json" }}
          paths: 
            - ~/.cache/puppeteer
            - ~/bichard7-next-tests/node_modules

################### Services
  start_audit_logging:
    steps:
      - run:
          name: Clone bichard7-next-audit-logging
          command: git clone --depth 1 git@github.com:ministryofjustice/bichard7-next-audit-logging.git ~/bichard7-next-audit-logging
      - run:
          name: Run bichard7-next-audit-logging
          working_directory: ~/bichard7-next-audit-logging
          environment:
            SKIP_PG: true
            SKIP_MQ: true
          background: true
          command: npm install && npm run start-api
      - run:
          name: Wait for bichard7-next-audit-logging
          working_directory: ~/bichard7-next-audit-logging
          command: npx wait-on http://localhost:3010/messages

  start_beanconnect:
    steps:
      - run:
          name: Start BeanConnect and PNC Emulator
          command: make run-beanconnect
      - run:
          name: Wait for Bichard
          command: bash ./scripts/wait_for_bichard.sh
      - run:
          name: Retry - start BeanConnect and PNC Emulator
          when: on_fail
          command: make run-beanconnect && bash ./scripts/wait_for_bichard.sh

#################################################################################

jobs:
  run_bichard_unit_tests:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    resource_class: xlarge
    steps:
      - checkout
      - build_data_jar
      - checkout_bichard_repo
      - build_bichard
      - run:
          name: Run Bichard unit tests
          working_directory: ~/bichard7-next
          command: make test

  run_e2e_tests:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    resource_class: xlarge
    environment:
      STACK_TYPE: next
      WORKSPACE: local-next
    parallelism: 4
    steps:
      - checkout
      - build_data_jar
      - checkout_bichard_repo
      - build_bichard
      - install_tests
      - fetch_docker_images
      - start_audit_logging
      - run:
          name: Start docker services (except BeanConnect)
          command: make run-all-no-bc && make run-ui
      - start_beanconnect
      - run:
          name: Run E2E tests
          working_directory: ~/bichard7-next-tests
          command: TOTAL_CHUNKS=$CIRCLE_NODE_TOTAL CHUNK_NUMBER=$CIRCLE_NODE_INDEX npm run test:chunk
      - save_e2e_artifacts

#################################################################################

workflows:
  version: 2
  test:
    jobs:
      - run_bichard_unit_tests
      - run_e2e_tests
