version: 2.1

commands:
  build_data_jar:
    description: Package the standing data into a jar file
    steps:
      - run:
          name: Package data with maven
          command: mvn package --no-transfer-progress

  checkout_bichard_repo:
    description: Check out the bichard7-next repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 34:9c:fd:c3:53:22:35:9e:07:60:6b:55:85:97:0d:18
      - run:
          name: Clone bichard7-next
          command: git clone git@github.com:ministryofjustice/bichard7-next.git ~/bichard7-next
      - run:
          name: Copy updated docker image fetch script
          working_directory: ~/bichard7-next
          command: cp scripts/fetch_docker_image.sh scripts/fetch_docker_image.sh.bak
      - run:
          name: Checkout previously working commit
          working_directory: ~/bichard7-next
          command: git checkout 59e653eadc69b2359c2c7463005b821f7faff514
      - run:
          name: Move updated docker image fetch script back
          working_directory: ~/bichard7-next
          command: mv scripts/fetch_docker_image.sh.bak scripts/fetch_docker_image.sh

  build_bichard:
    description: Build the Bichard application and copy in the latest standing data
    steps:
      - run:
          name: Copy data JAR into place
          command: |
            cp $(find ~/project/target -type f -name '*.jar' -and ! -name '*sources.jar') ~/bichard7-next/jars/bichard7-next-data.jar
      - run:
          name: Replace gradle data dependency with reference to local JAR
          working_directory: ~/bichard7-next
          command: |
            sed -i -r "s|^.*name: 'bichard7-next-data'.*$|    implementation files('../jars/bichard7-next-data.jar')|" bichard-backend/build.gradle
      - run:
          name: Build Bichard application
          working_directory: ~/bichard7-next
          command: make build-ci

  fetch_docker_image:
    parameters:
      image:
        type: string
      hash:
        type: string
        default: ""
    steps:
      - run:
          name: Fetch the <<parameters.image>> image
          working_directory: ~/bichard7-next
          command: bash scripts/fetch_docker_image.sh <<parameters.image>> <<parameters.image>> <<parameters.hash>>

  fetch_docker_images:
    description: Fetch all of the required docker images from ECR
    steps:
      - fetch_docker_image:
          image: beanconnect
          hash: sha256:1c3e16e00258915eef86d8b35f8bcbde67dd9859e0b199170815a920a349fd41
      - fetch_docker_image:
          image: e2etests
          hash: sha256:43c5b50926be2cfb5da6cc47075ef2b4caea5c768a1d383d36f3de6e2ecebac3
      - fetch_docker_image:
          image: nginx-auth-proxy
          hash: sha256:851a5146ff85057110c87c0f39e9c8728d2384b86c725822dd1d63b77d48acbe
      - fetch_docker_image:
          image: pncemulator
          hash: sha256:6a9fe30814f66015429794461e5a3050cf0b44030b12d832bca2c2f25b5543a0
      - fetch_docker_image:
          image: user-service
          hash: sha256:d0a81470fa3d81e6af0cb63d2b2196a746e60ecbe52f40faced1d2e8ea9836ba

  run_beanconnect_and_wait:
    steps:
      - run:
          name: Run BeanConnect and PNC emulator docker services
          command: make run-beanconnect
      - run:
          name: Wait for Bichard
          command: bash ./scripts/wait_for_bichard.sh
      - run:
          name: Try to run BeanConnect and PNC emulator docker services again
          command: make run-beanconnect && bash ./scripts/wait_for_bichard.sh
          when: on_fail

  run_e2e_test_chunk:
    steps:
      - run:
          name: Pipe logs to the test container
          command: bash ./.circleci/scripts/pipe_logs.sh liberty-next &> /tmp/logpipe.txt
          background: true
      - run:
          name: Run end-to-end tests
          working_directory: ~/bichard7-next
          command: make e2e-tests-record-chunk
          environment:
            TOTAL_CHUNKS: $CIRCLE_NODE_TOTAL
            CHUNK_NUMBER: $CIRCLE_NODE_INDEX
            STACK_TYPE: next
            BICHARD_REDIRECT_URL: https://172.17.0.1:9443/bichard-ui/Authenticate
            WORKSPACE: local-next
            RECORD: true
            AUTH_TYPE: bichard-jwt

  save_e2e_artifacts:
    steps:
      - run:
          name: Copy the artifacts from the image
          when: always
          command: docker cp $(docker ps -a -q --filter "name=e2e-tests" --filter "status=exited"):/src/screenshots ./screenshots
      - run:
          name: Compress the artifacts for easier downloading
          when: always
          command: for file in ./screenshots/*; do tar -czf ${file}.tar.gz $file; done
      - run:
          name: Create the saved_artifacts directory
          when: always
          command: mkdir ./saved_artifacts
      - run:
          name: Move the gzipped files across
          when: always
          command: mv ./screenshots/*.tar.gz ./saved_artifacts/
      - store_artifacts:
          path: /home/circleci/project/saved_artifacts

jobs:
  run_bichard_unit_tests:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    resource_class: xlarge
    steps:
      - checkout
      - build_data_jar
      - checkout_bichard_repo
      - build_bichard
      - run:
          name: Run Bichard unit tests
          working_directory: ~/bichard7-next
          command: make test

  run_e2e_tests:
    machine:
      image: ubuntu-2004:2022.07.1
      docker_layer_caching: false
    resource_class: xlarge
    working_directory: ~
    parallelism: 4
    steps:
      - checkout
      - build_data_jar
      - checkout_bichard_repo
      - build_bichard
      - fetch_docker_images
      - run:
          command: docker network prune -f
          name: Clear out the networks before we start our Docker services
      - run:
          name: Run full stack (excluding beanconnect and PNC emulator)
          working_directory: ~/bichard7-next
          command: make run-all-no-bc
      - run:
          name: Run beanconnect and PNC emulator
          working_directory: ~/bichard7-next
          command: make run-beanconnect
      - run:
          name: Wait for Bichard
          working_directory: ~/bichard7-next
          command: bash ./scripts/wait_for_bichard.sh
      - run:
          name: Wait 30 seconds for beanconnect to start
          command: sleep 30
      - run_e2e_test_chunk
      - save_e2e_artifacts

workflows:
  version: 2
  test:
    jobs:
      - run_bichard_unit_tests
      - run_e2e_tests
