version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  lint_and_build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - node/install
      - node/install-packages:
          include-branch-in-cache-key: true
      - run:
          name: Run linting
          command: npm run lint
      - run:
          name: Generate triggers.properties files
          command: npm run generate-trigger-config
      - run:
          name: Install output package NPM dependencies
          command: npm ci --ignore-scripts
          working_directory: output-data
      - run:
          name: Build output package
          command: npm run build
          working_directory: output-data

  build_data_jar:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Package data with Maven into a jar file
          command: mvn package --no-transfer-progress

workflows:
  test:
    jobs:
      - lint_and_build
      - build_data_jar
