name: Tests

on:
  push:

jobs:
  test_package:
    name: Test output-data package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Install NPM packages
        run: npm ci
      - name: Run tests
        run: npm test
