name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'output-data/**'
      - '.github/workflows/**'

jobs:
  release-packages:
    name: Release NPM and Maven packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Install top level NPM packages
        run: npm ci
      - name: Generate triggers.properties files
        run: npm run generate-trigger-config
      - name: Install NPM packages
        working-directory: output-data
        run: npm ci
      - name: Setup Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Build standing data
        working-directory: output-data
        run: npm run build
      - name: Release NPM and Maven Packages
        working-directory: output-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: npx semantic-release

  update-core-repo:
    needs: release-packages
    name: Update NPM package in core repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out core repo
        uses: actions/checkout@v3
        with:
          repository: ministryofjustice/bichard7-next-core
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Update standing data npm package
        run: npm install @moj-bichard7-developers/bichard7-next-data@latest
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto/update-standing-data
          delete-branch: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update standing data
          title: Update standing data
          body: >
            Automated standing data update generated by the
            [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml)
            workflow.
      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"

  update-b7-repo:
    needs: release-packages
    name: Update maven package in bichard7-next repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ministryofjustice/bichard7-next
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Update standing data maven package
        run: docker-compose run app gradle classes --no-daemon --parallel -g gradle-home --update-locks *:bichard7-next-data
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto/update-standing-data
          delete-branch: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update standing data
          title: Update standing data
          body: >
            Automated standing data update generated by the
            [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml)
            workflow.
      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
