name: Release
on:
  push:
    branches:
      - main
      - BICAWS-1878-publish-npm-package
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        working-directory: output-data
        run: npm ci
      - name: Build
        working-directory: output-data
        run: npm run build
      - name: Release
        working-directory: output-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
