name: Release
on:
  push:
    branches:
      - main
      - jamie/BICAWS-1801-always-release-on-main-branch

jobs:
  bump-package-version:
    name: Bump NPM package version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"

      - name: Bump output package version
        run: npm version patch
        working-directory: output-data

      - name: Commit output package version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add output-data/package*.json
          git commit -m "Bump package version"
          git push

  release-npm-package:
    name: Release NPM package
    needs: bump-package-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"

      - name: Install top-level NPM dependencies
        run: npm ci

      - name: Generate triggers.properties files
        run: npm run generate-trigger-config

      - name: Install output package NPM dependencies
        run: npm ci
        working-directory: output-data

      - name: Echo package version
        run: grep version output-data/package.json

      # - name: Publish output package
      #   run: npm publish
      #   working-directory: output-data

  release-maven-package:
    name: Release Maven package
    needs: bump-package-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      # - name: Publish maven package
      #   run: mvn compile exec:java && mvn compile versions:set deploy -P load-properties

  update-core-repo:
    name: Update NPM package in core repo
    needs: release-npm-package
    runs-on: ubuntu-latest
    steps:
      - name: Check out core repo
        uses: actions/checkout@v3
        with:
          repository: ministryofjustice/bichard7-next-core
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Update standing data npm package
        run: npm install @moj-bichard7-developers/bichard7-next-data@latest

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto/update-standing-data
          delete-branch: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update standing data
          title: Update standing data
          body: >
            Automated standing data update generated by the
            [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"

  update-b7-repo:
    name: Update maven package in bichard7-next repo
    needs: release-maven-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ministryofjustice/bichard7-next
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Update standing data maven package
        run: docker-compose run app gradle classes --no-daemon --parallel -g gradle-home --update-locks *:bichard7-next-data

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto/update-standing-data
          delete-branch: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update standing data
          title: Update standing data
          body: >
            Automated standing data update generated by the
            [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
