name: Release
on:
  push:
    branches:
      - BICAWS-1879-publish-maven-mackage
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install NPM packages
        working-directory: output-data
        run: npm ci
      - name: Build
        working-directory: output-data
        run: npm run build
      - name: Release NPM Package
        working-directory: output-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Release Maven Package
        env:
          USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: mvn clean compile exec:java -P generate-version-properties && mvn deploy -P deploy
