name: Release
on: workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  # bump-package-version:
  #   name: Bump NPM package version
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16.13.1"

  #     - name: Bump output package version
  #       run: npm version patch
  #       working-directory: output-data

  #     - name: Commit output package version bump
  #       run: |
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
  #         git add output-data/package*.json
  #         git commit -m "Bump package version"
  #         git push

  release-npm-package:
    name: Release NPM package
    needs: release-maven-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to specify the branch name, so that we get the updated package.json
          # If we don't specify this, the default is to fetch the commit that triggered
          # the workflow (which won't include the updated package.json)
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"

      - name: Install top-level NPM dependencies
        run: npm ci

      - name: Generate triggers.properties files
        run: npm run generate-trigger-config

      - name: Install output package NPM dependencies
        run: npm ci
        working-directory: output-data

      - name: Build output package
        working-directory: output-data
        run: npm run build

      - name: Publish output package
        run: npm publish
        working-directory: output-data
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-maven-package:
    name: Release Maven package
    # needs: bump-package-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # We need to specify the branch name, so that we get the updated package.json
          # If we don't specify this, the default is to fetch the commit that triggered
          # the workflow (which won't include the updated package.json)
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.1"

      - name: Install top-level NPM dependencies
        run: npm ci

      - name: Generate triggers.properties files
        run: npm run generate-trigger-config

      - name: Setup Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Generate version.properties
        run: mvn -q compile exec:java
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Check current directory
        run: pwd
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Output version.properties
        run: cat version.properties
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Update pom version
        run: mvn compile versions:set -P load-properties
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      
      - name: Check git status
        run: git status
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      
      - name: Output the POM
        run: cat pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Publish maven package
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  update-core-repo:
    name: Update NPM package in core repo
    needs: release-npm-package
    runs-on: ubuntu-latest
    steps:
      - name: Check out core repo
        uses: actions/checkout@v3
        with:
          repository: ministryofjustice/bichard7-next-core
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Update standing data npm package
        run: npm install @moj-bichard7-developers/bichard7-next-data@latest

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto/update-standing-data
          delete-branch: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update standing data
          title: Update standing data
          body: >
            Automated standing data update generated by the
            [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"

  update-b7-repo:
    name: Update maven package in bichard7-next repo
    needs: release-maven-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ministryofjustice/bichard7-next
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Update standing data maven package
        run: docker-compose run app gradle classes --no-daemon --parallel -g gradle-home --update-locks *:bichard7-next-data

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: auto/update-standing-data
          delete-branch: true
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: Update standing data
          title: Update standing data
          body: >
            Automated standing data update generated by the
            [Release](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/release.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number }}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
