name: Release
on:
  push:
    branches:
      - main
      - publish-package-to-npm-registry
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: Install dependencies
        working-directory: output-data
        run: npm ci
      - name: Build
        working-directory: output-data
        run: npm run build
      - name: Release
        working-directory: output-data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
