name: Update standing data

on:
  push:
    branches:
      - "Fix-offence-code-data-source"
jobs:
  update_standing_data:
    name: Update standing data
    runs-on: ubuntu-latest
    env:
      PNLD_DOWNLOAD_URL: ${{ secrets.PNLD_DOWNLOAD_URL }}
      PNLD_LOGIN_URL: ${{ secrets.PNLD_LOGIN_URL }}
      PNLD_PASSWORD: ${{ secrets.PNLD_PASSWORD }}
      PNLD_USERNAME: ${{ secrets.PNLD_USERNAME }}
      GOOGLE_API_KEY: ${{ secrets.SHEETSAPIKEY }}
      HEADLESS: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0

      - name: Install dependencies
        run: npm install

      - name: Download data files
        run: npm run download-external-data

      - name: Merge offence code data files
        run: npm run merge-offence-data

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto/update-data
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: 'fix(next-data): Update standing data'
          title: Update standing data
          body: >
            Automated standing data updates generated by the
            [Update standing data](https://github.com/ministryofjustice/bichard7-next-core/actions/workflows/update-standing-data.yml)
            workflow.
      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number}}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
