name: Update standing data

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update_standing_data:
    name: Update standing data
    runs-on: ubuntu-latest
    env:
      PNLD_DOWNLOAD_URL: ${{ secrets.PNLD_DOWNLOAD_URL }}
      PNLD_LOGIN_URL: ${{ secrets.PNLD_LOGIN_URL }}
      PNLD_PASSWORD: ${{ secrets.PNLD_PASSWORD }}
      PNLD_USERNAME: ${{ secrets.PNLD_USERNAME }}
      GOOGLE_API_KEY: ${{ secrets.SHEETSAPIKEY }}
      SD_USERNAME: ${{ secrets.SD_USERNAME }}
      SD_PASSWORD: ${{ secrets.SD_PASSWORD }}
      SD_END_POINT: ${{ secrets.SD_END_POINT }}
      HEADLESS: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup node version
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc

      - name: ⛓️ SLSA Supply Chain Security
        uses: ministryofjustice/devsecops-actions/sca/slsa@8c77d3a65a46d1d4b5416eafae5b84371ecd797d # v1.5.0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Download offence code data files
        run: npm run download-offence-code-data

      - name: Merge offence code data files
        run: npm run merge-offence-data

      - name: Download Organisation Unit data files
        run: npm run download-organisation-unit-data

      - name: Merge Organisation Unit data files
        run: npm run merge-organisation-unit-data

      - name: Download CJS result codes data file
        run: npm run download-cjs-result-codes-data

      - name: Merge CJS result codes data files
        run: npm run merge-cjs-result-codes-data

      - name: Report Status
        if: failure()
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d #v2.0.0
        with:
          webhook-type: incoming-webhook
          payload: |
            text: "GitHub action failed"  
            attachments:  
              - color: "#a30000" # Red  
                blocks:  
                  - type: "section"  
                    text:  
                      type: "mrkdwn"  
                      text: ":elmo-fire: *${{ github.workflow }}* failed in <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"  
                  - type: "context"  
                    elements:  
                      - type: "mrkdwn"  
                        text: "Linked to Repo <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        with:
          branch: auto/update-data
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          commit-message: "fix(next-data): Update standing data"
          title: Update standing data
          body: >
            Automated standing data updates generated by the
            [Update standing data](https://github.com/ministryofjustice/bichard7-next-data/actions/workflows/update-standing-data.yml)
            workflow.

      - name: Check PR information
        run: |
          echo "PR #${{ steps.cpr.outputs.pull-request-number}}"
          echo "${{ steps.cpr.outputs.pull-request-url }}"
